(function() {var implementors = {};
implementors['buf_redux'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='buf_redux/strategy/struct.IfEmpty.html' title='buf_redux::strategy::IfEmpty'>IfEmpty</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='buf_redux/strategy/struct.LessThan.html' title='buf_redux::strategy::LessThan'>LessThan</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='buf_redux/strategy/struct.AtEndLessThan1k.html' title='buf_redux::strategy::AtEndLessThan1k'>AtEndLessThan1k</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='buf_redux/strategy/struct.AtEndLessThan.html' title='buf_redux::strategy::AtEndLessThan'>AtEndLessThan</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='buf_redux/strategy/struct.NeverMove.html' title='buf_redux::strategy::NeverMove'>NeverMove</a>","impl&lt;R: <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a>, Rs: <a class='trait' href='buf_redux/strategy/trait.ReadStrategy.html' title='buf_redux::strategy::ReadStrategy'>ReadStrategy</a>, Ms: <a class='trait' href='buf_redux/strategy/trait.MoveStrategy.html' title='buf_redux::strategy::MoveStrategy'>MoveStrategy</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='buf_redux/struct.BufReader.html' title='buf_redux::BufReader'>BufReader</a>&lt;R, Rs, Ms&gt;","impl&lt;R: <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='buf_redux/struct.Unbuffer.html' title='buf_redux::Unbuffer'>Unbuffer</a>&lt;R&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
